# Generated by Django 3.0.8 on 2020-07-17 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('viName', models.CharField(max_length=128, unique=True)),
                ('enName', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'majors',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fullName', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('ethnic', models.CharField(max_length=20)),
                ('religion', models.CharField(max_length=20)),
                ('studyYear', models.IntegerField()),
                ('addressVN', models.CharField(max_length=128)),
                ('addressRu', models.CharField(max_length=128)),
                ('phone', models.IntegerField()),
                ('major', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='student.Major')),
            ],
        ),
    ]
