# Generated by Django 3.0.8 on 2020-07-17 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fullName',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Major'),
        ),
    ]
