# Generated by Django 3.0.8 on 2020-07-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200717_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='addressRu',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='addressVN',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ethnic',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='religion',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='studyYear',
            field=models.IntegerField(null=True),
        ),
    ]
